name: m_food
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.5.4+54

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  dropdown_button2: 2.0.0
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  flutter_plugin_android_lifecycle: 2.0.9
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  # google_maps: 6.3.0
  # google_maps_flutter: 2.2.6
  # google_maps_flutter_platform_interface: 2.2.6
  # google_maps_flutter_web: 0.4.0+8
  intl: 0.18.1
  json_path: 0.6.2
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  provider: 6.0.5
  shared_preferences: 2.0.15
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  signature: 5.3.2
  smooth_page_indicator: 1.0.1
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.8.4

  google_sign_in: ^6.1.4

  shimmer: ^3.0.0
  fluttertoast: ^8.2.2
  image_picker: ^1.0.2
  uuid: ^3.0.7
  flutter_spinkit: ^5.2.0

  double_back_to_close_app: ^2.1.0
  percent_indicator: ^4.2.3

  webview_flutter: ^4.2.4

  open_url: ^2.0.1
  flutter_html: ^3.0.0-beta.2

  carousel_slider: ^4.2.1

  flutter_pdfview: ^1.3.1
  flutter_cached_pdfview: ^0.4.2

  flutter_signature_pad: ^3.0.1


  # location: ^4.4.0
  # url_launcher: ^6.1.6
  map_launcher: ^2.4.0
  dio: ^4.0.6
  flutter_svg: ^2.0.7

  image_cropper: ^3.0.3
  photo_view: ^0.14.0
  image: ^4.0.17
  flutter_widget_from_html: ^0.10.3
  chewie: ^1.7.1
  flutter_datetime_picker_plus: ^2.1.0
  qr_flutter: ^4.1.0
  quickalert: ^1.0.2
  # share_plus: ^7.2.1
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.1

  share_plus: ^7.2.1

  live_activities: ^1.7.4

  mailer: ^6.0.1

  file_picker: ^6.1.1
  open_file: ^3.3.2

  flutter_dropdown_search: ^0.0.4




 #chat=====
  http: any
  # Date and Time
  # timeago: any
  # state management
  email_validator: ^2.1.17
  firebase_messaging: ^14.1.4
  flutter_local_notifications: ^12.0.4
  #=========s
  get: ^4.6.6
  firebase_dynamic_links: ^5.4.5

  firebase_app_check: ^0.2.1+8
  cloud_functions: ^4.5.8
  connectivity_plus: ^5.0.2
  dart_ping: ^9.0.1
  dart_ping_ios: ^4.0.2
  top_snackbar_flutter: ^3.1.0
  # scroll_date_picker: ^3.7.3
  # sn_progress_dialog: ^1.1.3


  flutter_typeahead: ^5.0.1

  geolocator: ^10.1.0
  intl_phone_number_input: ^0.7.3+1
  collection: ^1.17.2

  xml2json: ^6.2.2
  custom_pop_up_menu: ^1.2.4

  data_table_2: ^2.5.12

  # sn_progress_dialog: ^1.1.4

  scroll_date_picker: ^3.7.3

  awesome_dialog: ^3.2.1

  pie_chart: ^5.3.2
  community_charts_flutter: ^1.0.2
  fl_chart: ^0.64.0
  month_picker_dialog: ^2.0.2


dev_dependencies:
  # flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  # image: 4.0.17
  lints: 3.0.0

  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: 'assets/images/app_launcher_icon.jpg'


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.jpg
    - assets/thai_province_data.json.txt
    - assets/AMPHUR.json.txt
    - assets/DISTRICT.json.txt
    - assets/PROVINCE.json.txt
    - assets/LatLngZipCode.json.txt
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/images/logo-Mfood.png

  fonts:
    - family: MDIMenu
      fonts:
        - asset: assets/fonts/MDIMenu.ttf
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
    - family: Mfood2
      fonts:
        - asset: assets/fonts/Mfood2.ttf
    - family: MDIMenuV20
      fonts:
        - asset: assets/fonts/MDIMenu-v20.ttf
    - family: Ocr
      fonts:
        - asset: assets/fonts/OCR.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
